{
 "title": "Batfish FHRP Audit",
 "tags": [
  "batfish",
  "fhrp"
 ],
 "panels": [
  {
   "title": "Total FHRP Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (hostname,interface_name,protocol,group_id) ({fhrp=\"true\"}))"
    }
   ]
  },
  {
   "title": "All FHRP Configs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{fhrp=\"true\"}"
    }
   ]
  },
  {
   "title": "FHRP by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (protocol) (count_over_time({fhrp=\"true\"}[5m]))"
    }
   ]
  },
  {
   "title": "FHRP by Hostname",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (hostname) (count_over_time({fhrp=\"true\"}[5m]))"
    }
   ]
  }
 ]
}